name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    
    - name: Copy Server
      run: |
        mkdir release
        cp ./server/package.json ./release/package.json
        cp ./server/package-lock.json ./release/package-lock.json
        cp ./server/Dockerfile ./release/Dockerfile
        cp -r ./server/src ./release/src
        cp .gitignore ./release/.gitignore
    
      # cp ./server/Procfile ./release/Procfile
      # cp ./server/heroku.yml ./release/heroku.yml
    
    - name: Copy Client
      run: cp -r ./client ./release/src/

    - name: Deploy Container
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        cd release
        heroku container:login
        heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web
        heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web

    # - name: Deploy Git
    #   env: 
    #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    #   run: |
    #     cd release
    #     heroku login
    #     git init
    #     heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}
    #     git add .
    #     git commit -am "release"
    #     git push heroku master -f
    
    - name: Clean
      run: rm -rf ./release
